spring.application.name=movies
spring.data.mongodb.database=${env.MongoDatabase}
spring.data.mongodb.uri=mongodb+srv://${env.MongoUser}:${env.MongoPassword}@${env.MongoCluster}
server.port=${PORT:8080}
